#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

export DATABASE_URL="${DATABASE_URL:-postgresql://app:app@localhost:5432/placeholder}"

GARAGE_ENV_FILE="${GARAGE_ENV_FILE:-$SCRIPT_DIR/.garage.env}"

dc() {
  docker compose -f "$SCRIPT_DIR/../docker-compose.yml" --env-file "$GARAGE_ENV_FILE" "$@"
}

is_hex_64() {
  local value="${1:-}"
  [[ "$value" =~ ^[0-9a-f]{64}$ ]]
}

ensure_garage_env() {
  mkdir -p "$SCRIPT_DIR"

  local rpc_secret="" admin_token="" metrics_token=""
  if [[ -f "$GARAGE_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$GARAGE_ENV_FILE"
    rpc_secret="${GARAGE_RPC_SECRET:-}"
    admin_token="${GARAGE_ADMIN_TOKEN:-}"
    metrics_token="${GARAGE_METRICS_TOKEN:-}"
  fi

  local wrote=0

  if ! is_hex_64 "$rpc_secret"; then
    rpc_secret="$(openssl rand -hex 32)"
    wrote=1
  fi

  if [[ -z "$admin_token" ]]; then
    admin_token="$(openssl rand -hex 16)"
    wrote=1
  fi

  if [[ -z "$metrics_token" ]]; then
    metrics_token="$(openssl rand -hex 16)"
    wrote=1
  fi

  if [[ "$wrote" -eq 1 ]]; then
    cat >"$GARAGE_ENV_FILE" <<EOF
# This file is auto-generated by deployher's setup script.
# DO NOT EDIT THIS FILE MANUALLY.
GARAGE_RPC_SECRET=${rpc_secret}
GARAGE_ADMIN_TOKEN=${admin_token}
GARAGE_METRICS_TOKEN=${metrics_token}
EOF
    echo "Wrote Garage secrets to: $GARAGE_ENV_FILE"
  fi
}

wait_for_postgres() {
  echo "Waiting for Postgres..."
  for _ in {1..30}; do
    if dc exec -T postgres pg_isready -U app -d placeholder >/dev/null 2>&1; then
      echo "Postgres ready."
      return 0
    fi
    sleep 1
  done
  echo "Postgres failed to start in time."
  exit 1
}

wait_for_redis() {
  echo "Waiting for Redis..."
  for _ in {1..30}; do
    if dc exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
      echo "Redis ready."
      return 0
    fi
    sleep 1
  done
  echo "Redis failed to start in time."
  exit 1
}

wait_for_garage() {
  echo "Waiting for Garage..."
  local required=(
    "Listening on 0.0.0.0:3901"
    "S3 API server listening on http://0.0.0.0:3900"
    "K2V API server listening on http://0.0.0.0:3904"
    "Web server listening on http://0.0.0.0:3902"
    "Admin API server listening on http://0.0.0.0:3903"
  )

  for _ in {1..30}; do
    local logs
    logs="$(dc logs --no-color --tail 200 garage 2>&1 || true)"

    if [[ "$logs" == *"Cannot connect to the Docker daemon"* ]] || [[ "$logs" == *"docker.sock"* ]] || [[ "$logs" == *"permission denied"* ]]; then
      echo "Docker does not seem available (can't read container logs)."
      echo "Error:"
      echo "$logs"
      exit 1
    fi

    local ok=1
    for needle in "${required[@]}"; do
      if ! grep -Fq "$needle" <<<"$logs"; then
        ok=0
        break
      fi
    done

    if [[ "$ok" -eq 1 ]]; then
      echo "Garage ready."
      return 0
    fi
    sleep 1
  done
  echo "Garage failed to become healthy in time."
  exit 1
}

GARAGE_BUCKET_NAME="${GARAGE_BUCKET_NAME:-placeholder-bucket}"
GARAGE_KEY_NAME="${GARAGE_KEY_NAME:-devkey}"
BACKEND_ENV_FILE="$SCRIPT_DIR/../.env"

garage_cli() {
  docker exec garage /garage "$@" 2>&1 | grep -v -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' || true
}

ensure_garage_layout() {
  echo "Ensuring Garage cluster layout..."
  local status_output
  status_output="$(garage_cli status 2>&1 || true)"

  local node_id
  node_id="$(echo "$status_output" | grep -E '^[a-f0-9]{16}' | head -1 | awk '{print $1}')"

  if [[ -z "$node_id" ]]; then
    echo "Could not find Garage node ID from status output."
    return 1
  fi

  local has_capacity
  has_capacity="$(echo "$status_output" | grep -E '^[a-f0-9]{16}' | head -1 | grep -oE '[0-9.]+ [KMGT]?B' | head -1 || true)"

  if [[ -z "$has_capacity" ]]; then
    echo "Assigning layout to node $node_id..."
    garage_cli layout assign -z dc1 -c 1G "$node_id"

    local layout_show
    layout_show="$(garage_cli layout show 2>&1 || true)"

    local next_version
    next_version="$(echo "$layout_show" | grep -o '\-\-version [0-9]*' | awk '{print $2}' | head -1 || true)"

    if [[ -z "$next_version" ]]; then
      local current_version
      current_version="$(echo "$layout_show" | grep -i 'current.*version' | grep -o '[0-9]*' | head -1 || echo "0")"
      current_version="${current_version:-0}"
      next_version=$((current_version + 1))
    fi

    echo "Applying layout version $next_version..."
    garage_cli layout apply --version "$next_version"
    echo "Layout applied."

    echo "Waiting for layout to propagate..."
    sleep 2
  else
    echo "Layout already configured (node has capacity: $has_capacity)."
  fi
}

ensure_garage_bucket() {
  echo "Ensuring bucket '$GARAGE_BUCKET_NAME' exists..."
  local bucket_list
  bucket_list="$(garage_cli bucket list 2>&1 || true)"

  if echo "$bucket_list" | grep -qw "$GARAGE_BUCKET_NAME"; then
    echo "Bucket '$GARAGE_BUCKET_NAME' already exists."
  else
    garage_cli bucket create "$GARAGE_BUCKET_NAME"
    echo "Bucket '$GARAGE_BUCKET_NAME' created."
  fi
}

ensure_garage_key() {
  echo "Ensuring key '$GARAGE_KEY_NAME' exists..."
  local key_info
  key_info="$(garage_cli key info "$GARAGE_KEY_NAME" 2>&1 || true)"

  if echo "$key_info" | grep -q "Key ID"; then
    echo "Key '$GARAGE_KEY_NAME' already exists."
  else
    echo "Creating key '$GARAGE_KEY_NAME'..."
    key_info="$(garage_cli key create "$GARAGE_KEY_NAME" 2>&1)"
    echo "Key '$GARAGE_KEY_NAME' created."
  fi

  S3_ACCESS_KEY_ID="$(echo "$key_info" | grep -E 'Key ID' | sed 's/.*: *//' | tr -d '[:space:]')"

  # TODO: re-evaluate this
  echo "Fetching key secret..."
  local key_with_secret
  key_with_secret="$(garage_cli key info --show-secret "$GARAGE_KEY_NAME" 2>&1 || true)"
  S3_SECRET_ACCESS_KEY="$(echo "$key_with_secret" | grep -E 'Secret key' | sed 's/.*: *//' | tr -d '[:space:]')"

  echo "Parsed Key ID: $S3_ACCESS_KEY_ID"
  echo "Parsed Secret: ${S3_SECRET_ACCESS_KEY:0:8}... (truncated)"

  if [[ -z "$S3_ACCESS_KEY_ID" ]] || [[ -z "$S3_SECRET_ACCESS_KEY" ]]; then
    echo "Failed to parse key credentials."
    echo "Key info output:"
    echo "$key_info"
    echo "Key reveal output:"
    echo "$revealed"
    return 1
  fi

  echo "Allowing key '$GARAGE_KEY_NAME' on bucket '$GARAGE_BUCKET_NAME'..."
  garage_cli bucket allow --read --write "$GARAGE_BUCKET_NAME" --key "$GARAGE_KEY_NAME" >/dev/null 2>&1 || true
  echo "Key allowed on bucket."
}

inject_s3_env() {
  echo "Injecting S3 credentials into $BACKEND_ENV_FILE..."

  if [[ ! -f "$BACKEND_ENV_FILE" ]]; then
    cp "$BACKEND_ENV_FILE.example" "$BACKEND_ENV_FILE" 2>/dev/null || touch "$BACKEND_ENV_FILE"
  fi

  local tmp_file
  tmp_file="$(mktemp)"

  local has_bucket=false has_key_id=false has_secret=false

  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      S3_BUCKET=*)
        echo "S3_BUCKET=$GARAGE_BUCKET_NAME"
        has_bucket=true
        ;;
      S3_ACCESS_KEY_ID=*)
        echo "S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID"
        has_key_id=true
        ;;
      S3_SECRET_ACCESS_KEY=*)
        echo "S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY"
        has_secret=true
        ;;
      *)
        echo "$line"
        ;;
    esac
  done < "$BACKEND_ENV_FILE" > "$tmp_file"

  if [[ "$has_bucket" == false ]]; then echo "S3_BUCKET=$GARAGE_BUCKET_NAME" >> "$tmp_file"; fi
  if [[ "$has_key_id" == false ]]; then echo "S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID" >> "$tmp_file"; fi
  if [[ "$has_secret" == false ]]; then echo "S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY" >> "$tmp_file"; fi

  mv "$tmp_file" "$BACKEND_ENV_FILE"
  echo "S3 credentials injected."
}

setup_garage_s3() {
  ensure_garage_layout
  ensure_garage_bucket
  ensure_garage_key
  inject_s3_env
}

ensure_stack() {
  ensure_garage_env
  dc up -d garage postgres redis
  wait_for_postgres
  wait_for_redis
  wait_for_garage
  setup_garage_s3
}

cmd_start() {
  ensure_stack
  bun "$SCRIPT_DIR/../migrate.ts"
  bun "$SCRIPT_DIR/../seed.ts"
  echo "Stack started, DB migrated, data seeded."
}

cmd_stop() {
  ensure_garage_env
  dc down
}

cmd_reset() {
  ensure_garage_env
  dc down -v

  echo "Clearing Garage data and secrets..."
  rm -rf "$SCRIPT_DIR/meta" "$SCRIPT_DIR/data"
  rm -f "$GARAGE_ENV_FILE"

  ensure_stack
  bun "$SCRIPT_DIR/../migrate.ts"
  bun "$SCRIPT_DIR/../seed.ts"
  echo "Full reset complete (volumes recreated)."
}

cmd_migrate() {
  ensure_stack
  bun "$SCRIPT_DIR/../migrate.ts"
  echo "Migrations complete."
}

cmd_seed() {
  ensure_stack
  bun "$SCRIPT_DIR/../seed.ts"
  echo "Seeding complete."
}

cmd_logs() {
  ensure_garage_env
  dc logs -f
}

cmd_help() {
  echo "Usage: $0 {start|stop|reset|migrate|seed|logs}"
  echo ""
  echo "Commands:"
  echo "  start    start stack (postgres + redis + garage), migrate, seed"
  echo "  stop     stop containers only"
  echo "  reset    destroy volumes, recreate stack, migrate, seed"
  echo "  migrate  ensure stack running then run migrations"
  echo "  seed     ensure stack running then seed db"
  echo "  logs     follow stack logs"
  exit 0
}

case "${1:-}" in
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  reset)   cmd_reset ;;
  migrate) cmd_migrate ;;
  seed)    cmd_seed ;;
  logs)    cmd_logs ;;
  help|-h|--help|"") cmd_help ;;
  *) echo "Unknown command: $1" ; cmd_help ;;
esac
