#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$SCRIPT_DIR"

BUN_IMAGE="${BUN_IMAGE:-oven/bun:1.3.5}"

export DATABASE_URL="${DATABASE_URL:-postgresql://app:app@localhost:5432/placeholder}"

GARAGE_ENV_FILE="${GARAGE_ENV_FILE:-$SCRIPT_DIR/.garage.env}"

dc() {
  docker compose -f "$SCRIPT_DIR/../docker-compose.yml" --env-file "$GARAGE_ENV_FILE" "$@"
}

is_hex_64() {
  local value="${1:-}"
  [[ "$value" =~ ^[0-9a-f]{64}$ ]]
}

ensure_garage_env() {
  mkdir -p "$SCRIPT_DIR"

  local rpc_secret="" admin_token="" metrics_token=""
  if [[ -f "$GARAGE_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$GARAGE_ENV_FILE"
    rpc_secret="${GARAGE_RPC_SECRET:-}"
    admin_token="${GARAGE_ADMIN_TOKEN:-}"
    metrics_token="${GARAGE_METRICS_TOKEN:-}"
  fi

  local wrote=0

  if ! is_hex_64 "$rpc_secret"; then
    rpc_secret="$(openssl rand -hex 32)"
    wrote=1
  fi

  if [[ -z "$admin_token" ]]; then
    admin_token="$(openssl rand -hex 16)"
    wrote=1
  fi

  if [[ -z "$metrics_token" ]]; then
    metrics_token="$(openssl rand -hex 16)"
    wrote=1
  fi

  if [[ "$wrote" -eq 1 ]]; then
    cat >"$GARAGE_ENV_FILE" <<EOF
# This file is auto-generated by deployher's setup script.
# DO NOT EDIT THIS FILE MANUALLY.
GARAGE_RPC_SECRET=${rpc_secret}
GARAGE_ADMIN_TOKEN=${admin_token}
GARAGE_METRICS_TOKEN=${metrics_token}
EOF
    echo "Wrote Garage secrets to: $GARAGE_ENV_FILE"
  fi
}

wait_for_postgres() {
  echo "Waiting for Postgres..."
  for _ in {1..30}; do
    if dc exec -T postgres pg_isready -U app -d placeholder >/dev/null 2>&1; then
      echo "Postgres ready."
      return 0
    fi
    sleep 1
  done
  echo "Postgres failed to start in time."
  exit 1
}

wait_for_redis() {
  echo "Waiting for Redis..."
  for _ in {1..30}; do
    if dc exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
      echo "Redis ready."
      return 0
    fi
    sleep 1
  done
  echo "Redis failed to start in time."
  exit 1
}

wait_for_garage() {
  echo "Waiting for Garage..."
  local required=(
    "Listening on 0.0.0.0:3901"
    "S3 API server listening on http://0.0.0.0:3900"
    "K2V API server listening on http://0.0.0.0:3904"
    "Web server listening on http://0.0.0.0:3902"
    "Admin API server listening on http://0.0.0.0:3903"
  )

  for _ in {1..30}; do
    local logs
    logs="$(dc logs --no-color --tail 200 garage 2>&1 || true)"

    if [[ "$logs" == *"Cannot connect to the Docker daemon"* ]] || [[ "$logs" == *"docker.sock"* ]] || [[ "$logs" == *"permission denied"* ]]; then
      echo "Docker does not seem available (can't read container logs)."
      echo "Error:"
      echo "$logs"
      exit 1
    fi

    local ok=1
    for needle in "${required[@]}"; do
      if ! grep -Fq "$needle" <<<"$logs"; then
        ok=0
        break
      fi
    done

    if [[ "$ok" -eq 1 ]]; then
      echo "Garage ready."
      return 0
    fi
    sleep 1
  done
  echo "Garage failed to become healthy in time."
  exit 1
}

wait_for_nexus() {
  echo "Waiting for Nexus..."
  for _ in {1..180}; do
    if curl -fsS "http://127.0.0.1:8081/service/rest/v1/status" >/dev/null 2>&1; then
      echo "Nexus ready."
      return 0
    fi
    sleep 2
  done
  echo "Nexus failed to become healthy in time."
  dc logs --no-color --tail 200 nexus || true
  exit 1
}

GARAGE_BUCKET_NAME="${GARAGE_BUCKET_NAME:-placeholder-bucket}"
GARAGE_KEY_NAME="${GARAGE_KEY_NAME:-devkey}"
BACKEND_ENV_FILE="$REPO_ROOT/.env"

compose_postgres_network() {
  local cid
  cid="$(dc ps -q postgres 2>/dev/null | head -1)"
  if [[ -z "$cid" ]]; then
    echo "Postgres container not found. Is the stack up?" >&2
    return 1
  fi
  docker inspect -f '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}' "$cid" | head -1
}

run_bun_script() {
  local script_name="$1"
  if [[ ! -f "$BACKEND_ENV_FILE" ]]; then
    echo "Missing $BACKEND_ENV_FILE — copy .env.example and configure it." >&2
    return 1
  fi
  local net
  net="$(compose_postgres_network)" || return 1
  [[ -n "$net" ]] || {
    echo "Could not resolve Docker network for Postgres." >&2
    return 1
  }
  echo "Running $script_name in $BUN_IMAGE (Docker)..."
  docker run --rm \
    --network "$net" \
    -v "$REPO_ROOT:/usr/src/app" \
    -w /usr/src/app \
    --env-file "$BACKEND_ENV_FILE" \
    -e DATABASE_URL=postgresql://app:app@postgres:5432/placeholder \
    "$BUN_IMAGE" \
    sh -lc "set -euo pipefail; bun install --frozen-lockfile && bun $script_name"
}

bun_nexus_eula_disclaimer() {
  docker run --rm -i "$BUN_IMAGE" bun -e \
    'const input = await new Response(Bun.stdin.stream()).text(); const parsed = JSON.parse(input); process.stdout.write(typeof parsed.disclaimer === "string" ? parsed.disclaimer : "");'
}

bun_nexus_eula_payload() {
  docker run --rm -i "$BUN_IMAGE" bun -e \
    'const disclaimer = await new Response(Bun.stdin.stream()).text(); process.stdout.write(JSON.stringify({ accepted: true, disclaimer }));'
}

garage_cli() {
  docker exec garage /garage "$@" 2>&1 | grep -v -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' || true
}

ensure_garage_layout() {
  echo "Ensuring Garage cluster layout..."
  local status_output
  status_output="$(garage_cli status 2>&1 || true)"

  local node_id
  node_id="$(echo "$status_output" | grep -E '^[a-f0-9]{16}' | head -1 | awk '{print $1}')"

  if [[ -z "$node_id" ]]; then
    echo "Could not find Garage node ID from status output."
    return 1
  fi

  local has_capacity
  has_capacity="$(echo "$status_output" | grep -E '^[a-f0-9]{16}' | head -1 | grep -oE '[0-9.]+ [KMGT]?B' | head -1 || true)"

  if [[ -z "$has_capacity" ]]; then
    echo "Assigning layout to node $node_id..."
    garage_cli layout assign -z dc1 -c 1G "$node_id"

    local layout_show
    layout_show="$(garage_cli layout show 2>&1 || true)"

    local next_version
    next_version="$(echo "$layout_show" | grep -o '\-\-version [0-9]*' | awk '{print $2}' | head -1 || true)"

    if [[ -z "$next_version" ]]; then
      local current_version
      current_version="$(echo "$layout_show" | grep -i 'current.*version' | grep -o '[0-9]*' | head -1 || echo "0")"
      current_version="${current_version:-0}"
      next_version=$((current_version + 1))
    fi

    echo "Applying layout version $next_version..."
    garage_cli layout apply --version "$next_version"
    echo "Layout applied."

    echo "Waiting for layout to propagate..."
    sleep 2
  else
    echo "Layout already configured (node has capacity: $has_capacity)."
  fi
}

ensure_garage_bucket() {
  echo "Ensuring bucket '$GARAGE_BUCKET_NAME' exists..."
  local bucket_list
  bucket_list="$(garage_cli bucket list 2>&1 || true)"

  if echo "$bucket_list" | grep -qw "$GARAGE_BUCKET_NAME"; then
    echo "Bucket '$GARAGE_BUCKET_NAME' already exists."
  else
    garage_cli bucket create "$GARAGE_BUCKET_NAME"
    echo "Bucket '$GARAGE_BUCKET_NAME' created."
  fi
}

ensure_garage_key() {
  echo "Ensuring key '$GARAGE_KEY_NAME' exists..."
  local key_info
  key_info="$(garage_cli key info "$GARAGE_KEY_NAME" 2>&1 || true)"

  if echo "$key_info" | grep -q "Key ID"; then
    echo "Key '$GARAGE_KEY_NAME' already exists."
  else
    echo "Creating key '$GARAGE_KEY_NAME'..."
    key_info="$(garage_cli key create "$GARAGE_KEY_NAME" 2>&1)"
    echo "Key '$GARAGE_KEY_NAME' created."
  fi

  S3_ACCESS_KEY_ID="$(echo "$key_info" | grep -E 'Key ID' | sed 's/.*: *//' | tr -d '[:space:]')"

  # TODO: re-evaluate this
  echo "Fetching key secret..."
  local key_with_secret
  key_with_secret="$(garage_cli key info --show-secret "$GARAGE_KEY_NAME" 2>&1 || true)"
  S3_SECRET_ACCESS_KEY="$(echo "$key_with_secret" | grep -E 'Secret key' | sed 's/.*: *//' | tr -d '[:space:]')"

  echo "Parsed Key ID: $S3_ACCESS_KEY_ID"
  echo "Parsed Secret: ${S3_SECRET_ACCESS_KEY:0:8}... (truncated)"

  if [[ -z "$S3_ACCESS_KEY_ID" ]] || [[ -z "$S3_SECRET_ACCESS_KEY" ]]; then
    echo "Failed to parse key credentials."
    echo "Key info output:"
    echo "$key_info"
    echo "Key reveal output:"
    echo "$revealed"
    return 1
  fi

  echo "Allowing key '$GARAGE_KEY_NAME' on bucket '$GARAGE_BUCKET_NAME'..."
  garage_cli bucket allow --read --write "$GARAGE_BUCKET_NAME" --key "$GARAGE_KEY_NAME" >/dev/null 2>&1 || true
  echo "Key allowed on bucket."
}

inject_s3_env() {
  echo "Injecting S3 credentials into $BACKEND_ENV_FILE..."

  if [[ ! -f "$BACKEND_ENV_FILE" ]]; then
    cp "$REPO_ROOT/.env.example" "$BACKEND_ENV_FILE" 2>/dev/null || touch "$BACKEND_ENV_FILE"
  fi

  local tmp_file
  tmp_file="$(mktemp)"

  local has_bucket=false has_key_id=false has_secret=false

  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      S3_BUCKET=*)
        echo "S3_BUCKET=$GARAGE_BUCKET_NAME"
        has_bucket=true
        ;;
      S3_ACCESS_KEY_ID=*)
        echo "S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID"
        has_key_id=true
        ;;
      S3_SECRET_ACCESS_KEY=*)
        echo "S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY"
        has_secret=true
        ;;
      *)
        echo "$line"
        ;;
    esac
  done < "$BACKEND_ENV_FILE" > "$tmp_file"

  if [[ "$has_bucket" == false ]]; then echo "S3_BUCKET=$GARAGE_BUCKET_NAME" >> "$tmp_file"; fi
  if [[ "$has_key_id" == false ]]; then echo "S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID" >> "$tmp_file"; fi
  if [[ "$has_secret" == false ]]; then echo "S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY" >> "$tmp_file"; fi

  mv "$tmp_file" "$BACKEND_ENV_FILE"
  echo "S3 credentials injected."
}

setup_garage_s3() {
  ensure_garage_layout
  ensure_garage_bucket
  ensure_garage_key
  inject_s3_env
}

wait_for_app() {
  echo "Waiting for app container..."
  for _ in {1..45}; do
    if dc ps --status running --services 2>/dev/null | grep -qx "app"; then
      echo "App container running."
      return 0
    fi
    sleep 1
  done
  echo "App container failed to start in time."
  dc logs --no-color --tail 200 app || true
  exit 1
}

wait_for_build_worker() {
  echo "Waiting for deployment-worker container..."
  for _ in {1..45}; do
    if dc ps --status running --services 2>/dev/null | grep -qx "deployment-worker"; then
      echo "Deployment-worker container running."
      return 0
    fi
    sleep 1
  done
  echo "Deployment-worker container failed to start in time."
  dc logs --no-color --tail 200 deployment-worker || true
  exit 1
}

verify_build_worker_docker_access() {
  echo "Verifying Docker access inside deployment-worker container..."

  local which_output
  if ! which_output="$(dc exec -T deployment-worker sh -lc 'which docker' 2>&1)"; then
    echo "Docker CLI is not available in deployment-worker container."
    echo "$which_output"
    exit 1
  fi

  local docker_ps_output
  if ! docker_ps_output="$(dc exec -T deployment-worker sh -lc 'docker ps >/dev/null' 2>&1)"; then
    echo "Deployment-worker container cannot access Docker daemon via /var/run/docker.sock."
    echo "$docker_ps_output"
    exit 1
  fi

  echo "Docker access OK inside deployment-worker container."
}

read_nexus_env() {
  if [[ ! -f "$BACKEND_ENV_FILE" ]]; then
    return 1
  fi
  NEXUS_REGISTRY="$(grep -E '^NEXUS_REGISTRY=' "$BACKEND_ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' | tr -d "'" || true)"
  NEXUS_USER="$(grep -E '^NEXUS_USER=' "$BACKEND_ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' | tr -d "'" || true)"
  NEXUS_PASSWORD="$(grep -E '^NEXUS_PASSWORD=' "$BACKEND_ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' | tr -d "'" || true)"
  [[ -n "$NEXUS_REGISTRY" ]] && [[ -n "$NEXUS_USER" ]] && [[ -n "$NEXUS_PASSWORD" ]]
}

nexus_api() {
  local method="$1"
  local path="$2"
  local user="$3"
  local password="$4"
  local body="${5:-}"
  shift 5 || true

  local -a args=(
    -fsS
    -u "$user:$password"
    -X "$method"
    "http://127.0.0.1:8081${path}"
  )

  if [[ -n "$body" ]]; then
    args+=(-H "Content-Type: application/json" -d "$body")
  fi

  curl "${args[@]}"
}

ensure_nexus_admin_password() {
  if ! read_nexus_env; then
    return 0
  fi

  if [[ ${#NEXUS_PASSWORD} -lt 8 ]]; then
    echo "NEXUS_PASSWORD must be at least 8 characters for Nexus bootstrap."
    exit 1
  fi

  if nexus_api GET "/service/rest/v1/status" "$NEXUS_USER" "$NEXUS_PASSWORD" >/dev/null 2>&1; then
    echo "Nexus admin credentials already valid."
    return 0
  fi

  local initial_password=""
  for _ in {1..30}; do
    initial_password="$(docker exec nexus sh -lc 'cat /nexus-data/admin.password 2>/dev/null' | tr -d '\r' || true)"
    if [[ -n "$initial_password" ]]; then
      break
    fi
    sleep 2
  done

  if [[ -z "$initial_password" ]]; then
    echo "Could not read Nexus initial admin password from /nexus-data/admin.password."
    exit 1
  fi

  echo "Setting Nexus admin password from initial bootstrap password..."
  if ! curl -fsS \
    -u "admin:$initial_password" \
    -X PUT \
    "http://127.0.0.1:8081/service/rest/v1/security/users/admin/change-password" \
    -H "Content-Type: text/plain" \
    --data "$NEXUS_PASSWORD" >/dev/null; then
    echo "Failed to set Nexus admin password."
    exit 1
  fi

  echo "Nexus admin password configured."
}

ensure_nexus_eula() {
  if ! read_nexus_env; then
    return 0
  fi

  local eula
  eula="$(nexus_api GET "/service/rest/v1/system/eula" "$NEXUS_USER" "$NEXUS_PASSWORD" "" || true)"
  if grep -q '"accepted"[[:space:]]*:[[:space:]]*true' <<<"$eula"; then
    echo "Nexus EULA already accepted."
    return 0
  fi

  local disclaimer
  disclaimer="$(printf '%s' "$eula" | bun_nexus_eula_disclaimer)"
  if [[ -z "$disclaimer" ]]; then
    echo "Failed to read Nexus EULA disclaimer."
    exit 1
  fi

  echo "Accepting Nexus Community Edition EULA..."
  local payload
  payload="$(printf '%s' "$disclaimer" | bun_nexus_eula_payload)"
  nexus_api POST "/service/rest/v1/system/eula" "$NEXUS_USER" "$NEXUS_PASSWORD" "$payload" >/dev/null
  echo "Nexus EULA accepted."
}

ensure_nexus_docker_realm() {
  if ! read_nexus_env; then
    return 0
  fi

  local active
  active="$(nexus_api GET "/service/rest/v1/security/realms/active" "$NEXUS_USER" "$NEXUS_PASSWORD" "" || true)"
  if grep -q '"DockerToken"' <<<"$active"; then
    echo "Nexus Docker Bearer Token Realm already active."
    return 0
  fi

  echo "Activating Nexus Docker Bearer Token Realm..."
  nexus_api PUT \
    "/service/rest/v1/security/realms/active" \
    "$NEXUS_USER" \
    "$NEXUS_PASSWORD" \
    '["NexusAuthenticatingRealm","DockerToken"]' >/dev/null
  echo "Nexus Docker Bearer Token Realm activated."
}

ensure_nexus_docker_repo() {
  if ! read_nexus_env; then
    return 0
  fi

  local repos
  repos="$(nexus_api GET "/service/rest/v1/repositories" "$NEXUS_USER" "$NEXUS_PASSWORD" || true)"
  if grep -Eq '"name"[[:space:]]*:[[:space:]]*"docker-hosted"' <<<"$repos"; then
    echo "Nexus docker-hosted repository already exists."
    return 0
  fi

  echo "Creating Nexus docker-hosted repository on port 8082..."
  local payload='{"name":"docker-hosted","online":true,"storage":{"blobStoreName":"default","strictContentTypeValidation":true,"writePolicy":"ALLOW"},"docker":{"v1Enabled":false,"forceBasicAuth":true,"httpPort":8082}}'
  if ! nexus_api POST "/service/rest/v1/repositories/docker/hosted" "$NEXUS_USER" "$NEXUS_PASSWORD" "$payload" >/dev/null; then
    echo "Failed to create Nexus docker-hosted repository."
    exit 1
  fi

  echo "Nexus docker-hosted repository created."
}

ensure_nexus_ready() {
  if ! read_nexus_env; then
    return 0
  fi

  wait_for_nexus
  ensure_nexus_admin_password
  ensure_nexus_eula
  ensure_nexus_docker_realm
  ensure_nexus_docker_repo
}

ensure_nexus_login() {
  if ! read_nexus_env; then
    return 0
  fi

  ensure_nexus_ready

  echo "Logging in to Nexus registry $NEXUS_REGISTRY..."
  if echo "$NEXUS_PASSWORD" | docker login "$NEXUS_REGISTRY" -u "$NEXUS_USER" --password-stdin 2>/dev/null; then
    echo "Nexus login OK."
  else
    echo "Nexus login failed. Deployment worker may not be able to pull images from $NEXUS_REGISTRY."
  fi
}

ensure_nexus_images() {
  if ! read_nexus_env; then
    return 0
  fi

  echo "Syncing build images to Nexus $NEXUS_REGISTRY..."

  local -a images=(
    "node:22-bookworm"
    "oven/bun:1"
    "python:3.12-bookworm"
    "nginx:alpine"
  )

  for img in "${images[@]}"; do
    echo "Pushing $img..."
    docker pull "$img" 2>/dev/null || true
    docker tag "$img" "$NEXUS_REGISTRY/$img"
    docker push "$NEXUS_REGISTRY/$img"
  done

  echo "Building pdploy-node-build-image..."
  docker build \
    -f "$SCRIPT_DIR/../docker/node-builder.Dockerfile" \
    --build-arg "NEXUS_REGISTRY=$NEXUS_REGISTRY" \
    -t "$NEXUS_REGISTRY/pdploy-node-build-image:latest" \
    "$SCRIPT_DIR/.."

  echo "Pushing pdploy-node-build-image..."
  docker push "$NEXUS_REGISTRY/pdploy-node-build-image:latest"

  echo "Building pdploy-bun-build-image..."
  docker build \
    -f "$SCRIPT_DIR/../docker/bun-builder.Dockerfile" \
    --build-arg "NEXUS_REGISTRY=$NEXUS_REGISTRY" \
    -t "$NEXUS_REGISTRY/pdploy-bun-build-image:latest" \
    "$SCRIPT_DIR/.."

  echo "Pushing pdploy-bun-build-image..."
  docker push "$NEXUS_REGISTRY/pdploy-bun-build-image:latest"

  echo "Nexus images synced."
}

ensure_app_stack() {
  ensure_nexus_login
  ensure_nexus_images
  echo "Building and starting app services..."
  dc up -d --build node-build-image bun-build-image app deployment-worker
  wait_for_app
  wait_for_build_worker
  verify_build_worker_docker_access
}

ensure_stack() {
  ensure_garage_env
  dc up -d garage postgres redis nexus
  wait_for_postgres
  wait_for_redis
  wait_for_garage
  ensure_nexus_ready
  setup_garage_s3
}

cmd_start() {
  ensure_stack
  run_bun_script migrate.ts
  run_bun_script seed.ts
  ensure_app_stack
  echo "Stack started (infra + app + deployment-worker), DB migrated, data seeded."
}

cmd_stop() {
  ensure_garage_env
  dc down
}

cmd_reset() {
  ensure_garage_env
  dc down -v

  echo "Clearing Garage data and secrets..."
  rm -rf "$SCRIPT_DIR/meta" "$SCRIPT_DIR/data"
  rm -f "$GARAGE_ENV_FILE"

  ensure_stack
  run_bun_script migrate.ts
  run_bun_script seed.ts
  ensure_app_stack
  echo "Full reset complete (volumes recreated, app + deployment-worker rebuilt)."
}

cmd_migrate() {
  ensure_stack
  run_bun_script migrate.ts
  echo "Migrations complete."
}

cmd_seed() {
  ensure_stack
  run_bun_script seed.ts
  echo "Seeding complete."
}

cmd_logs() {
  ensure_garage_env
  dc logs -f
}

cmd_help() {
  echo "Usage: $0 {start|stop|reset|migrate|seed|logs}"
  echo ""
  echo "Requires Docker (and docker compose). Migrate/seed run via $BUN_IMAGE — no Bun on the host."
  echo ""
  echo "Commands:"
  echo "  start    start stack (postgres + redis + garage + app + deployment-worker), migrate, seed"
  echo "  stop     stop containers only"
  echo "  reset    destroy volumes, recreate stack, migrate, seed, rebuild app + deployment-worker"
  echo "  migrate  ensure stack running then run migrations"
  echo "  seed     ensure stack running then seed db"
  echo "  logs     follow stack logs"
  exit 0
}

case "${1:-}" in
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  reset)   cmd_reset ;;
  migrate) cmd_migrate ;;
  seed)    cmd_seed ;;
  logs)    cmd_logs ;;
  help|-h|--help|"") cmd_help ;;
  *) echo "Unknown command: $1" ; cmd_help ;;
esac
