package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/lewinbobda/deployher/golang/picoclaw-deployer/internal/deployer"
)

func main() {
	opts := parseFlags()

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	result, err := deployer.Deploy(ctx, opts)
	if err != nil {
		fail("%v", err)
	}

	if result.Options.PrintOnly {
		fmt.Printf("docker %s\n", strings.Join(result.DockerArgs, " "))
		return
	}

	fmt.Printf("Started PicoClaw container %q using %s mode.\n", result.ContainerName, result.Options.Mode)
	fmt.Printf("Image: %s\n", result.Image)
	fmt.Printf("Data dir: %s\n", result.DataDir)
	fmt.Printf("Config: %s\n", result.ConfigPath)
	fmt.Printf("Gateway: http://127.0.0.1:%d\n", result.Options.GatewayPort)
	if result.Options.Mode == deployer.ModeLauncher {
		fmt.Printf("Launcher UI: http://127.0.0.1:%d\n", result.Options.LauncherPort)
		if strings.TrimSpace(result.Options.DashboardToken) == "" {
			fmt.Printf("Launcher token: autogenerated on startup; inspect with: docker logs %s\n", result.ContainerName)
		}
	}
	if result.CreatedConfig {
		fmt.Printf("Created starter config with placeholder credentials at %s\n", result.ConfigPath)
	}
	fmt.Printf("Logs: docker logs -f %s\n", result.ContainerName)
}

func parseFlags() deployer.Options {
	var opts deployer.Options

	flag.StringVar(&opts.Name, "name", "", "Docker container name (defaults to picoclaw-gateway or picoclaw-launcher)")
	flag.Func("mode", "Deployment mode: gateway or launcher", func(value string) error {
		opts.Mode = deployer.Mode(strings.ToLower(strings.TrimSpace(value)))
		return nil
	})
	flag.StringVar(&opts.Image, "image", "", "Override Docker image")
	flag.StringVar(&opts.DataDir, "data-dir", "", "Host directory mounted into /root/.picoclaw (default: ./picoclaw-data)")
	flag.StringVar(&opts.GatewayHost, "gateway-host", "", "Gateway listen host inside the container (default: 0.0.0.0)")
	flag.IntVar(&opts.GatewayPort, "gateway-port", 0, "Host port mapped to PicoClaw gateway port 18790")
	flag.IntVar(&opts.LauncherPort, "launcher-port", 0, "Host port mapped to PicoClaw launcher UI port 18800")
	flag.StringVar(&opts.DashboardToken, "dashboard-token", "", "Fixed launcher dashboard token; launcher mode only")
	flag.BoolVar(&opts.Pull, "pull", false, "Run `docker pull` before starting the container")
	flag.BoolVar(&opts.Replace, "replace", false, "Remove an existing container with the same name before redeploying")
	flag.BoolVar(&opts.PrintOnly, "print-only", false, "Print the docker command instead of executing it")

	flag.Parse()
	return opts
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
