import fs from "node:fs/promises";
import path from "node:path";
import type { CliContext } from "../types";
import { readEnvValue } from "./env-file";
import { compose } from "./compose";
import { runCommand } from "./run";
import { injectS3IntoEnvFile, envExamplePath } from "./s3-inject";

export const randomHex = (byteLength: number): string => {
  const buf = new Uint8Array(byteLength);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
};

const isHex64 = (v: string): boolean => /^[0-9a-f]{64}$/.test(v);

export const ensureGarageEnv = async (
  ctx: CliContext,
  log: (m: string) => void,
): Promise<void> => {
  await fs.mkdir(ctx.infraDir, { recursive: true });
  await fs.mkdir(path.join(ctx.infraDir, "meta"), { recursive: true });
  await fs.mkdir(path.join(ctx.infraDir, "data"), { recursive: true });
  let rpc = "";
  let admin = "";
  let metrics = "";
  try {
    const raw = await fs.readFile(ctx.garageEnvFile, "utf8");
    rpc = readEnvValue(raw, "GARAGE_RPC_SECRET") ?? "";
    admin = readEnvValue(raw, "GARAGE_ADMIN_TOKEN") ?? "";
    metrics = readEnvValue(raw, "GARAGE_METRICS_TOKEN") ?? "";
  } catch {
    /* missing file */
  }

  let wrote = false;
  if (!isHex64(rpc)) {
    rpc = randomHex(32);
    wrote = true;
  }
  if (!admin) {
    admin = randomHex(16);
    wrote = true;
  }
  if (!metrics) {
    metrics = randomHex(16);
    wrote = true;
  }

  if (wrote) {
    const body = `# This file is auto-generated by deployher's setup script.
# DO NOT EDIT THIS FILE MANUALLY.
GARAGE_RPC_SECRET=${rpc}
GARAGE_ADMIN_TOKEN=${admin}
GARAGE_METRICS_TOKEN=${metrics}
`;
    await fs.writeFile(ctx.garageEnvFile, body, "utf8");
    log(`Wrote Garage secrets to: ${ctx.garageEnvFile}`);
  }
};

export const filterGarageTimestampLines = (text: string): string =>
  text
    .split("\n")
    .filter((l) => !/^\d{4}-\d{2}-\d{2}T/.test(l))
    .join("\n");

export const garageExec = async (ctx: CliContext, garageArgs: string[]): Promise<string> => {
  const r = await runCommand(["docker", "exec", "garage", "/garage", ...garageArgs], {
    cwd: ctx.repoRoot,
  });
  const combined = `${r.stdout}\n${r.stderr}`;
  return filterGarageTimestampLines(combined).trim();
};

export const parseGarageNodeId = (statusOutput: string): string | undefined => {
  const line = statusOutput.split("\n").find((l) => /^[a-f0-9]{16}/i.test(l.trim()));
  return line?.trim().split(/\s+/)[0];
};

export const parseGarageCapacity = (statusOutput: string): string | undefined => {
  const line = statusOutput.split("\n").find((l) => /^[a-f0-9]{16}/i.test(l.trim()));
  if (!line) return undefined;
  const m = line.match(/[0-9.]+\s+[KMGT]?B/);
  return m?.[0];
};

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export const ensureGarageLayout = async (
  ctx: CliContext,
  log: (m: string) => void,
): Promise<void> => {
  log("Ensuring Garage cluster layout...");
  const statusOutput = await garageExec(ctx, ["status"]);

  const nodeId = parseGarageNodeId(statusOutput);
  if (!nodeId) {
    throw new Error("Could not find Garage node ID from status output.");
  }

  const hasCapacity = parseGarageCapacity(statusOutput);
  if (!hasCapacity) {
    log(`Assigning layout to node ${nodeId}...`);
    await garageExec(ctx, ["layout", "assign", "-z", "dc1", "-c", "1G", nodeId]);

    let layoutShow = await garageExec(ctx, ["layout", "show"]);
    let nextVersion = layoutShow.match(/--version\s+(\d+)/)?.[1];
    if (!nextVersion) {
      const currentMatch = layoutShow.match(/current.*version[^\d]*(\d+)/i);
      const currentVersion = currentMatch?.[1] ? parseInt(currentMatch[1], 10) : 0;
      nextVersion = String(currentVersion + 1);
    }

    log(`Applying layout version ${nextVersion}...`);
    await garageExec(ctx, ["layout", "apply", "--version", nextVersion]);
    log("Layout applied.");
    log("Waiting for layout to propagate...");
    await sleep(2000);
  } else {
    log(`Layout already configured (node has capacity: ${hasCapacity}).`);
  }
};

export const ensureGarageBucket = async (
  ctx: CliContext,
  log: (m: string) => void,
): Promise<void> => {
  const name = ctx.garageBucketName;
  log(`Ensuring bucket '${name}' exists...`);
  const bucketList = await garageExec(ctx, ["bucket", "list"]);
  const hasBucket = bucketList.split("\n").some((line) => line.trim().split(/\s+/).includes(name));
  if (hasBucket) {
    log(`Bucket '${name}' already exists.`);
    return;
  }
  await garageExec(ctx, ["bucket", "create", name]);
  log(`Bucket '${name}' created.`);
};

export type GarageKeyCreds = { accessKeyId: string; secretAccessKey: string };

export const ensureGarageKey = async (
  ctx: CliContext,
  log: (m: string) => void,
): Promise<GarageKeyCreds> => {
  const keyName = ctx.garageKeyName;
  log(`Ensuring key '${keyName}' exists...`);
  let keyInfo = await garageExec(ctx, ["key", "info", keyName]);

  if (!/Key ID/i.test(keyInfo)) {
    log(`Creating key '${keyName}'...`);
    keyInfo = await garageExec(ctx, ["key", "create", keyName]);
    log(`Key '${keyName}' created.`);
  } else {
    log(`Key '${keyName}' already exists.`);
  }

  const keyIdLine = keyInfo.split("\n").find((l) => /Key ID/i.test(l));
  const accessKeyId = keyIdLine?.replace(/^.*?:\s*/, "").replace(/\s/g, "") ?? "";

  log("Fetching key secret...");
  const keyWithSecret = await garageExec(ctx, ["key", "info", "--show-secret", keyName]);
  const secretLine = keyWithSecret.split("\n").find((l) => /Secret key/i.test(l));
  const secretAccessKey = secretLine?.replace(/^.*?:\s*/, "").replace(/\s/g, "") ?? "";

  log(`Parsed Key ID: ${accessKeyId}`);
  log(`Parsed Secret: ${secretAccessKey.slice(0, 8)}... (truncated)`);

  if (!accessKeyId || !secretAccessKey) {
    throw new Error(
      `Failed to parse key credentials.\nKey info output:\n${keyInfo}\nKey reveal output:\n${keyWithSecret}`,
    );
  }

  log(`Allowing key '${keyName}' on bucket '${ctx.garageBucketName}'...`);
  await runCommand(
    [
      "docker",
      "exec",
      "garage",
      "/garage",
      "bucket",
      "allow",
      "--read",
      "--write",
      ctx.garageBucketName,
      "--key",
      keyName,
    ],
    { cwd: ctx.repoRoot },
  );
  log("Key allowed on bucket.");

  return { accessKeyId, secretAccessKey };
};

export const setupGarageS3 = async (
  ctx: CliContext,
  log: (m: string) => void,
): Promise<void> => {
  await ensureGarageLayout(ctx, log);
  await ensureGarageBucket(ctx, log);
  const creds = await ensureGarageKey(ctx, log);
  log(`Injecting S3 credentials into ${ctx.backendEnvFile}...`);
  await injectS3IntoEnvFile(
    ctx.backendEnvFile,
    envExamplePath(ctx.repoRoot),
    ctx.garageBucketName,
    creds.accessKeyId,
    creds.secretAccessKey,
  );
  log("S3 credentials injected.");
};

export const clearGarageLocalData = async (ctx: CliContext): Promise<void> => {
  await fs.rm(`${ctx.infraDir}/meta`, { recursive: true, force: true });
  await fs.rm(`${ctx.infraDir}/data`, { recursive: true, force: true });
  await fs.unlink(ctx.garageEnvFile).catch(() => undefined);
};

export const getPostgresDockerNetwork = async (ctx: CliContext): Promise<string> => {
  const ps = await compose(ctx, ["ps", "-q", "postgres"]);
  if (!ps.ok) {
    throw new Error("Postgres container not found. Is the stack up?");
  }
  const cid = ps.stdout.trim().split("\n")[0]?.trim();
  if (!cid) {
    throw new Error("Postgres container not found. Is the stack up?");
  }
  const ins = await runCommand(
    [
      "docker",
      "inspect",
      "-f",
      "{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}",
      cid,
    ],
    { cwd: ctx.repoRoot },
  );
  if (!ins.ok) {
    throw new Error("Could not resolve Docker network for Postgres.");
  }
  const net = ins.stdout.trim().split("\n")[0]?.trim();
  if (!net) {
    throw new Error("Could not resolve Docker network for Postgres.");
  }
  return net;
};
